name: cicd_frontend
on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push
        run: |
          cd front_despacho
          docker build -t innovatech-frontend .
          docker tag innovatech-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Despliegue SSM
        run: |
          aws ssm send-command \
          --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":[
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
            "docker stop front-innovatech || true",
            "docker rm front-innovatech || true",
            "docker run -d --name front-innovatech -p 80:80 ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
          ]}'
