name: cicd_backends

on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push
        run: |
          cd back-Despachos_SpringBoot
          docker build -t innovatech-backend .
          docker tag innovatech-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Despliegue SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_BACKEND_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --region us-east-1 \
            --parameters '{"commands":[
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest",
              "docker stop back-innovatech || true",
              "docker rm back-innovatech || true",
              "docker run -d --name back-innovatech -p 8080:8080 ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
            ]}'
